export const projectsTranslations = {
    svlfg: 'Ein externes Projekt, bei dem ich hauptsächlich das Team berate, wie man SAP Composable Storefront und Angular nutzt. Meine Rolle besteht darin, qualitativ hochwertigen Code sicherzustellen, die besten Ansätze zu implementieren und das Projekt in ein Mono-Repository umzuwandeln, um eine neue zweite App einzuführen und die gemeinsame Funktionalität in Bibliotheken zu extrahieren, die von beiden Apps genutzt werden können.',
    mobilcom: 'Ein externes Projekt, bei dem ich für die Implementierung der neuen Relaunch-Dashboard-Seite verantwortlich war, damit Kunden ihre Verträge, Datenverwendung, Rechnungen, Marketing und mehr überprüfen können. Meine Aufgaben umfassten die Zusammenarbeit mit dem Designer und dem Projektmanager, um ihre Vision umzusetzen, die erforderlichen Jira-Tickets zur Zielerreichung zu erstellen und mit dem Entwicklungsteam von Mobilcom zusammenzuarbeiten, um meine Lösung nahtlos in ihre Unternehmenslösung zu integrieren.',
    emporix: 'Eine agnostische  Poly-Repository-Integration, die mithilfe des von <a href="https://github.com/vuestorefront">Alokai</a> bereitgestellten <a href="https://github.com/vuestorefront/integration-boilerplate">integration-boilerplate</a> entwickelt wurde. Ziel war es, ein Integrations-SDK für <a href="https://www.emporix.com/">Emporix</a> bereitzustellen, bei dem mein Arbeitskollege und ich eine Hauptrolle beim Legen der Grundlagen für das Projekt spielten, indem ich die erforderlichen Pakete einrichtete und die Emporix-Authentifizierungs-API implementierte.',
    haba: 'Meine Aufgabe war es, die Leistung des Online-Shops unserer Kunden zu verbessern und gleichzeitig die Wartungskosten zu senken. Die Shops hatten lange Ladezeiten, weil zu viel ungenutzter JavaScript-Code vorhanden war und keine effizienten Caching-Strategien genutzt wurden. Um das zu beheben, habe ich Strategien entwickelt, um den Code beim Start um 20% zu reduzieren, indem ich überflüssigen Code identifizierte, der später geladen werden konnte. Außerdem hat der Kunde beschlossen, die Shops vom SAP Composable Storefront zu trennen, um Kosten zu sparen, aber wichtige Funktionen beizubehalten. Um das zu erleichtern, habe ich den nötigen Code aus dem SAP Composable Storefront extrahiert und in eine eigene Bibliothek organisiert. Dadurch wurde nicht nur die Funktionalität bewahrt, sondern die Größe des geladenen Codes um weitere 10% reduziert.',
    ottos: 'Ein externes Projekt, bei dem ich als Projektleiter für das Frontend-Team eingeteilt wurde, um das Unternehmen Valantic bei der Zusammenarbeit mit dem Team neusta zu unterstützen. Unser Ziel war es, neue Online-Shops für Ottos.ch und Sherpa Outdoors zu entwickeln, wobei wir eine einheitliche Codebasis mit unterschiedlichen Themen und Konfigurationen nutzen. In dieser Funktion habe ich das Ticketmanagement zwischen unseren Teams koordiniert, technische Anforderungen verfasst und Unterstützung zu Themen im Zusammenhang mit dem SAP composable Storefront bereitgestellt.',
    landgard: 'Meine Rolle bestand hauptsächlich darin, eine einheitliche Codebasis für die B2B-Online-Shops von Landgard und Ordertage umzusetzen und mit dem Backend-Team zusammenzuarbeiten. Bei Mein Schöner Garten habe ich meinen Kollegen während der Entwicklung geholfen und bei Bedarf Fehler behoben.',
    spar: 'Ein externes Projekt, bei dem ich mit dem Spar-Team zusammengearbeitet habe, um die Funktionalitäten im ungarischen Spar Online-Shop zu erweitern und gleichzeitig den Shop barrierefrei zu machen.',
    dachdecker: 'den Shop pflegen und mit neuen Funktionen erweitern',
    supplix: 'den Shop pflegen und mit neuen Funktionen erweitern',
    daw: 'Ein großer Kunde mit 13 verschiedenen online Shops. Meine Aufgabe bestand darin, neue Funktionen für die einheitliche Codebasis aller 13 Shops zu implementieren und einige Funktionalitäten für spezifische Geschäfte anzupassen.'
}
