export const projectsTranslations = {
    svlfg: 'An external project where I am primarily consulting the team on utilizing SAP Composable Storefront and Angular. My role involves ensuring high-quality code, implementing the best approaches, and converting the project into a mono-repo to introduce a new second app and extract the shared functionality into libraries to be consumed by both apps.',
    mobilcom: 'An external project, where I was responsible for implementing the new relaunch dashboard page for customers, where they could check their contracts, data usage, invoices, marketing, and more. My tasks included collaborating with the designer and project manager to fulfill their vision, creating the necessary Jira tickets to achieve the goal, and working with the Mobilcom development team to seamlessly embed my solution into their enterprise solution.',
    emporix: 'An agnostic poly-repo integration, which is built using the <a href="https://github.com/vuestorefront/integration-boilerplate">integration-boilerplate</a> provided by <a href="https://github.com/vuestorefront">Alokai</a>, aimed to provide an integration sdk for <a href="https://www.emporix.com/">Emporix</a> ,where my colleague and I played a key role in laying the groundwork for the project by setting up the needed packages and implementing the Emporix authentication API',
    haba: 'My role involved enhancing the performance of our client\'s shops while simultaneously reducing maintenance costs. The shops were experiencing long loading times, mainly due to an excess of unused JavaScript code and the lack of caching strategies. To address this issue, I implemented strategies to reduce the initial load code by 20%, identifying and unused initial code that could be loaded lazily. Additionally, in order to minimize expenses, the client opted to decouple their shops from the SAP composable storefront while retaining essential functionality. To facilitate this transition, I extracted the necessary code from the SAP composable storefront, organizing it into a dedicated library. This not only preserved functionality but also resulted in a further 10% reduction in the size of both shops.',
    ottos: 'An external project, where I was assigned to be the project frontend lead to support the company Valantic collaborating with team neusta. Our objective was to develop new online shops for both Ottos.ch and Sherpa Outdoors utilizing a unified codebase with different theming and configuration. In this capacity, I orchestrated ticket management among our teams, authored technical requirements, and provided support on SAP composable storefront-related matters.',
    landgard: 'My primary focus was on developing a cohesive codebase for the B2B online shops of Landgard and Ordertage, and to cooperate and define the technical requirements with the backend team. Within the scope of my responsibilities at Mein Schöner Garten, I provided assistance to colleagues during development as needed and addressed bug fixes.',
    spar: 'An external project where I collaborated with  the spar team to expand functionalities within the Hungarian Spar online shop, while also enhancing accessibility on the frontend.',
    dachdecker: 'Maintain and enhance the shop by introducing new features',
    supplix: 'Maintain and enhance the shop by introducing new features',
    daw: 'A huge client with 13 different shops. My role involved implementing new features for the unified codebase across all 13 shops and customizing certain functionalities for specific shops.'
}
